---
title: "PowerDataRStudio2Ejercicios"
author: "Elena Bravo"
date: "2/23/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## *Ejercicio 1: Definir una Función sin Parámetros* 

#Enunciado: Define una función llamada saludo que imprima en la consola el mensaje "Hola, bienvenido a R". 

saludo <- function(x){
  resultado <- "Hola, bienvenido a R"
  return(resultado)
}

print(saludo(x))

```

```{r}

## *Ejercicio 2: Definir una Función con Parámetros y Condicionales**
# Enunciado: Crea una función llamada calificar_edad que tome un parámetro numérico llamado edad y muestre en la consola si la persona es "menor de edad" o "mayor de edad". 

calificar_edad <- function(edad) {
 if ( edad < 18) {
   print("Menor de edad")
 } else {
   print("Mayor edad")
 } }

calificar_edad(14)
```

```{r}
## *Ejercicio 3: Bucle con Operaciones Aritméticas*
#Enunciado: Define una función llamada tabla_multiplicar que tome un parámetro numérico n e imprima la tabla de multiplicar del 1 al 10 de ese número. 

tabla_multiplicar <- function(n) {
  for(i in 1:10) {
    print(n*i)}}


tabla_multiplicar(3)
```

```{r}

## *Ejercicio 4: Bucle con Condicionales y Operaciones con Vectores*

#Enunciado: Crea una función llamada numeros_pares que tome un parámetro numérico limite e imprima los números pares hasta ese límite. 

n <- 10
numeros_pares <- c()
  for (i in 1:n) {
    if (i %% 2) {
      next    }
    print(i)
  }

```

```{r}

## *Ejercicio 5: Bucle Anidado con Condicionales y Operaciones de Listas*

#Enunciado: Define una función llamada matriz_cuadrada que tome un parámetro numérico n e imprima una matriz cuadrada de tamaño n x n donde los elementos son el resultado de la suma de sus índices de fila y columna.


matriz_cuadrada <- function(n) {
  resultado <- sqrt(n)
  return(resultado)
}

print(matriz_cuadrada(5))
```

